#!/usr/bin/env php
<?php

declare(strict_types=1);

use yii\console\Application;

if (!file_exists(__DIR__ . '/.production')) {
    defined('YII_DEBUG') or define('YII_DEBUG', true);
    defined('YII_ENV') or define('YII_ENV', 'dev');
}

require(__DIR__ . '/vendor/autoload.php');
require(__DIR__ . '/vendor/yiisoft/yii2/Yii.php');

$config = require(__DIR__ . '/config/console.php');

$application = new Application($config);
$exitCode = $application->run();
exit($exitCode);
