---
name: 'CI'
on:
  - 'push'
jobs:
  phpSyntaxCheck:
    name: 'PHP Syntax Check'
    strategy:
      matrix:
        php_version:
          - '7.3'
          - '7.4'
          - '8.0'
    runs-on: 'ubuntu-20.04'
    steps:
      - uses: 'actions/checkout@v2'
      - run: |
          sudo update-alternatives --set php /usr/bin/php${{ matrix.php_version }}
          php -v
          find . \( -type d \( -name '.git' -or -name 'vendor' -or -name 'runtime' \) -prune \) -or \( -type f -name '*.php' -print \) | LANG=C sort | xargs -n 1 php -l

  phpStyleCheck:
    name: 'PHP Coding Style'
    runs-on: 'ubuntu-20.04'
    steps:
      - uses: 'actions/checkout@v2'
      - run: |
          sudo update-alternatives --set php /usr/bin/php7.4
          curl -fsSL -o phpcs "https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar"
          php -v
          php phpcs --version
          php phpcs --standard=phpcs.xml --encoding=UTF-8 --runtime-set ignore_warnings_on_exit 1

  jsStyleCheck:
    name: 'JS Coding Style'
    runs-on: 'ubuntu-20.04'
    steps:
      - uses: 'actions/checkout@v2'
      - run: |
          node --version
          npm ci
          npx eslint "web/js/*.es"

  cssStyleCheck:
    name: 'CSS Coding Style'
    runs-on: 'ubuntu-20.04'
    steps:
      - uses: 'actions/checkout@v2'
      - run: |
          node --version
          npm ci
          npx stylelint "web/css/*.scss"
